name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Instead of using GITHUB_REPOSITORY directly, use just the repository name without the owner.
    - name: Lowercase the repo name
      run: echo "REPO=${GITHUB_REPOSITORY##*/}" >>${GITHUB_ENV}

    # the order of the tags in this configuration does not matter.
    - name: build and push container to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          pandapanda3/huggingface-azure-acr:latest
          pandapanda3/huggingface-azure-acr:${{ env.REPO }}-${{ github.sha }}